version: "2.29.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ahmedsakr98/first-node-docker-compose:jenkins
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["npm", "start"]